sudo: required
services:
- docker
language: c
cache:
  directories:
  - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps
- stack install --local-bin-path .
after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ -n "$TRAVIS_TAG" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker build -t deadleg/docker-event-emitter:$TRAVIS_TAG .;
  docker build -t deadleg/docker-event-emitter:latest .;
  docker push deadleg/docker-event-emitter:$TRAVIS_TAG;
  docker push deadleg/docker-event-emitter:latest; fi
deploy:
  provider: releases
  api_key:
    secure: F/gzLoTKORQMpUUch+ut/fTIC0lVtJROvPSV/YxHtm41mzqF9jdpweN1MQAOzQCN7vb4eQZR0WJAY3DDBo4/VURlKtVAlosHdbJo8xYnNEIMVpJL5dqVm7WfLAdo5d31KgSwGx08ydQoBCibSguU6pM37/+bA1eVITSeZ7gTv8aThYr/hWIzk4OJKCBpIniv42nypwKOZf9tL07Lknvotiak/L8pBz12rU0ZSyTqHj+qz1U5vbb2FBc6odrYolmhpBZOhQhsVV/vGCCd4K4O7nR0UIjBfUItJbkrGelcmYAhQcKAqotB1X39yIRietxth8OUcdxJrOhXNt/DtQycWZZij1PsVa4/4V2YFcD9CvxUYZEQU4i03bMRflqtks9wViBcny2g1a7jR8wLuNn29aibixKKmG1gJw+9aWX431PN95RZtbeahsQ8taJs7eWT/XHEIisu5NzI5633HKKbIAOASf4svtRQ5kHbz65mPW5CK9UOK1AIrZVmpbR5u/VyiwA99GLl2gJdxQwTRg66zuPerCfETxwZHbgnBV6CtUepKCri/DPPWtJcOq1PWOmY5Dl/+RGCHxGidW3b+w6atGdnqezPrrjQIinvBz0j5DaZaawA39Hi0g8F6e++RQiiwGsaJTP1Yvki7+/IrBfoBUkR0Aocj8x9pDLgueJPDX8=
  file: docker-event-emitter
  skip_cleanup: true
  on:
    tags: true
